### ISSUE TITLE
ConnectionFactory is not being decorated since there is no bundle being registered

### ISSUE THREAD

**Issue by belmeopmenieuwesim** [fwolfsjaeger/doctrine-cockroachdb-bundle#1]
At the moment the bundle repo only consts of 1 file `ConnectionFactory`. In order to properly register this service from vendor to the main application container it needs to be wrapped in an actual Symfony bundle, which will load any additional services.

**Comment by fwolfsjaeger** [comment]
Yes, you are right of course, I just didn't have the time to implement it properly yet ;)

I'll continue working on it in August. You're welcome to amend it as well if you want.
